### ISSUE TITLE
List data types that are accepted

### ISSUE THREAD

**Issue by oriordanemily** [lexixu19/Duplexity#5]
https://github.com/lexixu19/Duplexity/blob/7b08fd06ee0eac882d8b60f87f189d91793aeb6c/duplexity/utils.py#L35

Can we add an error message like:
'Unsupported data type: data received was {type(data)}, expected one of np.array, xr.DataArray, pd.DataFrame, List[Union[xr.DataArray, xr.Dataset, pd.DataFrame]]'

**Comment by lexixu19** [comment]
Done.

**Comment by oriordanemily** [comment]
Lexi implemented this in https://github.com/lexixu19/Duplexity/commit/dc86c6b1373b983075d3870d2cf9fe75dcb2d1c5
